---
- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install OpenJDK
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
  become: yes

- name: Add Jenkins repository key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  become: yes

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
    filename: jenkins
    update_cache: yes
  become: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  tags: jenkins
  become: yes

- name: Wait for Jenkins initial admin password file
  wait_for:
    path: /var/lib/jenkins/secrets/initialAdminPassword
    state: present
    timeout: 180

- name: Read Jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_initial_pw
  changed_when: false
  failed_when: jenkins_initial_pw.rc != 0

- name: Print Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_initial_pw.stdout }}"

