pipeline {
    agent any
    
    environment {
        IMAGE_NAME = "alia153/jenkins-ivolve"
    }
    
    tools {
        maven 'mvn'  // أو الاسم اللي ضفته في Global Tool Configuration
    }
    
    stages {
        stage('Cloning the repo') {
            steps {
                git url: 'https://github.com/Aliabdrabo/iVolve-DevOps.git', branch: 'main'
            }
        }
        
        stage('Run Unit Test') {
            steps {
                sh "cd Jenkins_App"
                sh "mvn test"
            }
        }
        
        stage('Build the app') {
            steps {
                sh "mvn package"
            }
        }
        
        stage('Build Docker image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:v${BUILD_NUMBER} ."
            }
        }
        
        stage('Push Docker image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin"
                    sh "docker push ${IMAGE_NAME}:v${BUILD_NUMBER}"
                }
            }
        }
        
        stage('Delete image locally') {
            steps {
                sh "docker rmi ${IMAGE_NAME}:v${BUILD_NUMBER}"
            }
        }
        
        stage('Update Deployment') {
            steps {
                sh "sed -i 's|image:.*|image: ${IMAGE_NAME}:v${BUILD_NUMBER}|' deployment.yaml"
            }
        }
        
        stage('Deploy to Kubernetes') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
                    sh "kubectl apply -f deployment.yaml"
                }
            }
        }
    }  
    
    post {  
        success {
            echo "✅ Pipeline succeeded!"
        }
        failure {
            echo "❌ Pipeline failed!"
        }
        always {
            echo "🔄 Pipeline finished!"
        }
    }
}
